export const SEARCH_PHOTO = 'SEARCH_PHOTO';
export const SEARCH_PHOTO_SUCCESS = 'SEARCH_PHOTO_FAILURE';
export const GET_PHOTO_DETAILS = 'GET_PHOTO_DETAILS';
export const GET_PHOTO_DETAILS_SUCCESS = 'GET_PHOTO_DETAILS_SUCCESS';